{
 "title": "Container Resources",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "containers", "query": "container_last_seen" },
   { "name": "container_regex" }
  ]
 },
 "panels": [
  {
   "title": "Container CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(container_cpu_user_seconds_total{name=~\".*$container_regex.*\"}[1m]))",
     "legendFormat": "{{name}} {{instance}}"
    }
   ]
  },
  {
   "title": "Container RAM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, container_memory_usage_bytes{name=~\".*$container_regex.*\"})",
     "legendFormat": "{{name}} {{instance}}"
    }
   ]
  },
  {
   "title": "Filesystem Free Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "bottomk(10, container_fs_limit_bytes{name=~\".*$container_regex.*\"}-container_fs_usage_bytes{name=~\".*$container_regex.*\"})",
     "legendFormat": "{{name}} {{device}} {{instance}}"
    }
   ]
  },
  {
   "title": "Network Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(container_network_receive_bytes_total{name=~\".*$container_regex.*\"}[3m]))",
     "legendFormat": "IN {{name}} {{instance}}"
    },
    {
     "expr": "- topk(10, rate(container_network_transmit_bytes_total{name=~\".*$container_regex.*\"}[3m]))",
     "legendFormat": "OUT {{name}} {{instance}}"
    }
   ]
  },
  {
   "title": "Filesystem Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(container_fs_writes_bytes_total{name=~\".*$container_regex.*\"}[2m]))",
     "legendFormat": "WRITE {{name}} {{device}} {{instance}}"
    },
    {
     "expr": "- topk(10, rate(container_fs_reads_bytes_total{name=~\".*$container_regex.*\"}[2m]))",
     "legendFormat": "READ {{name}} {{device}} {{instance}}"
    }
   ]
  },
  {
   "title": "Network Drop/Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(container_network_receive_errors_total{name=~\".*$container_regex.*\"}[2m]))",
     "legendFormat": "RECEIVE ERROR {{name}} {{device}} {{instance}}"
    },
    {
     "expr": "-topk(10, rate(container_network_transmit_errors_total{name=~\".*$container_regex.*\"}[2m]))",
     "legendFormat": "TRANSMIT ERROR {{name}} {{device}} {{instance}}"
    },
    {
     "expr": "topk(10, rate(container_network_receive_packets_dropped_total{name=~\".*$container_regex.*\"}[2m]))",
     "legendFormat": "RECEIVE DROPPED {{name}} {{device}} {{instance}}"
    },
    {
     "expr": "-topk(10, rate(container_network_transmit_packets_dropped_total{name=~\".*$container_regex.*\"}[2m]))",
     "legendFormat": "TRANSMIT DROPPED {{name}} {{device}} {{instance}}"
    }
   ]
  },
  {
   "title": "Filesystem IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(container_fs_writes_total{name=~\".*$container_regex.*\"}[2m]))",
     "legendFormat": "WRITE {{name}} {{device}} {{instance}}"
    },
    {
     "expr": "- topk(10, rate(container_fs_reads_total{name=~\".*$container_regex.*\"}[2m]))",
     "legendFormat": "READ {{name}} {{device}} {{instance}}"
    }
   ]
  }
 ]
}