{
 "title": "Overall Awareness",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Node CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) by (instance)) / count (node_cpu_seconds_total{mode=\"idle\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Network Drops",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_drop_total[3m])) by (instance) + sum(rate(node_network_receive_drop_total[3m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(node_network_transmit_err_total[3m])) by (instance) + sum(rate(node_network_receive_err_total[3m])) by (instance)",
     "legendFormat": "{{instance}} err"
    }
   ]
  },
  {
   "title": "Node RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "repeat": "node_id",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)/node_memory_MemTotal_bytes)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Volume Storage Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(3, (1-(node_filesystem_avail_bytes{fstype=\"xfs\"}/node_filesystem_size_bytes{fstype=\"xfs\"})))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "OOM kills",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(node_vmstat_oom_kill[1m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Container count",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(container_last_seen)" }
   ]
  },
  {
   "title": "Instantiations (30m)",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "container_start_time_seconds>(time()-30*60)"
    }
   ]
  },
  {
   "title": "Reaching max memory",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "container_memory_rss/container_memory_max_usage_bytes>0.8"
    }
   ]
  },
  {
   "title": "Reaching max CPU (Throttled)",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total[5m])>0.1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum((node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"} * 100) / count(node_meta * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"})"
    },
    {}
   ]
  }
 ]
}